// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLvcGU738c8AzoNwSqWCUb6TrBxXQOc-8',
    appId: '1:410283081088:web:1b79be4e0ab226507e9565',
    messagingSenderId: '410283081088',
    projectId: 'mundo-web-ff0ac',
    authDomain: 'mundo-web-ff0ac.firebaseapp.com',
    storageBucket: 'mundo-web-ff0ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvK__ScoZryMPBVVy04MkPHL4dOCnB8bk',
    appId: '1:410283081088:android:21d66a7dd49d506f7e9565',
    messagingSenderId: '410283081088',
    projectId: 'mundo-web-ff0ac',
    storageBucket: 'mundo-web-ff0ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1NRQ-VRZvDlh1hIf9u9geWK0FqMC7TyE',
    appId: '1:410283081088:ios:d8ef1da9dcfaa84a7e9565',
    messagingSenderId: '410283081088',
    projectId: 'mundo-web-ff0ac',
    storageBucket: 'mundo-web-ff0ac.appspot.com',
    iosClientId: '410283081088-ele3u92vsfticmn33o0e57lgqa3jofsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1NRQ-VRZvDlh1hIf9u9geWK0FqMC7TyE',
    appId: '1:410283081088:ios:d8ef1da9dcfaa84a7e9565',
    messagingSenderId: '410283081088',
    projectId: 'mundo-web-ff0ac',
    storageBucket: 'mundo-web-ff0ac.appspot.com',
    iosClientId: '410283081088-ele3u92vsfticmn33o0e57lgqa3jofsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
